name: Create tag if renovate pushed a commit

on:
  push:
    branches:
    - main

jobs:
  load-version-envs:
    uses: ./.github/workflows/load-version-envs.yaml

  tag:
    runs-on: ubuntu-latest
    needs: load-version-envs
    steps:
    - name: Store commit author
      id: commit_author
      run: |
        echo "Commit author: ${{ github.event.head_commit.author.name }}"
        echo "Author email: ${{ github.event.head_commit.author.email }}"
        echo "Jenkins version: ${{ needs.load-version-envs.outputs.jenkins-version }}"

    - name: Get the last tag
      id: last_tag
      run: |
        last_tag=$(git describe --tags --abbrev=0 || echo "${{ needs.load-version-envs.outputs.jenkins-version }}-v0.0.0")
        echo "Last tag: $last_tag"
        echo "last_tag=$last_tag" >> $GITHUB_OUTPUT
