name: Create tag if renovate pushed a commit

on:
  push:
    branches:
    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Get the last tag
      id: get-last-tag
      run: |
        last_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "Last tag: ${last_tag}"
        echo "tag=${last_tag}" >> ${GITHUB_OUTPUT}

    - name: Create new patch version
      if: github.event.head_commit.author.name == 'renovate-bot'
      run: |
        tag="$(awk -F. '/[0-9]+\./{$NF+=1;print}' OFS=. <<< "${{ steps.get-last-tag.outputs.tag }}")"

        git tag "${tag}"
        git push origin "${tag}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
